title = "Pier"

[port]
pprof = 4455{{.Id}}

[log]
level = "info"
dir = "logs"
filename = "pier.log"
report_caller = false

[mode]
type = "{{.Mode}}" # relay or direct
[mode.relay]
addr = "{{.Bitxhub}}"
quorum = 2
validators = [
    {{.Validators}}
]
[mode.direct]
peers = [{{.Peers}}]

[appchain]
plugin = "{{.PluginFile}}"
config = "{{.PluginConfig}}"
